Gemfile.lock, app/controllers/offers_controller.rb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, config/routes.rb, test/controllers/offers_controller_test.rb
réalisation du controller offers
=> réalisation du controller offers

Gemfile, Gemfile.lock, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20221121204059_add_devise_to_users.rb, db/schema.rb
la page de login fonctionne je pull request
=> réalisation du devise

app/controllers/offers_controller.rb, app/models/user.rb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, db/seeds.rb
réalisation de la navbar malabar du bings
=> réalisation de la navbar malabar du bings

app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, db/migrate/20221121182112_create_users.rb, db/migrate/20221121182113_create_offers.rb, db/migrate/20221121182540_create_bookings.rb, db/migrate/20221121182541_create_reviews.rb, db/schema.rb, db/seeds.rb
seed complétée par la création de 4 user + création d'offers avec l'id du user en dynamique
=> seed-user-faite

app/controllers/bookings_controller.rb, app/models/offer.rb, app/models/review.rb
Signed-off-by: Stephane Chaigneau <stephanechaigneau@gmail.com>
=> relation-modele

app/controllers/bookings_controller.rb, app/models/booking.rb, app/models/offer.rb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, config/routes.rb, db/seeds.rb
=> seed-booking

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/offers_controller.rb, app/javascript/controllers/address_autocomplete_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/models/offer.rb, app/views/layouts/application.html.erb, app/views/offers/_info_window.html.erb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, config/initializers/geocoder.rb, db/migrate/20221122184316_add_coordinates_to_offers.rb, db/schema.rb, db/seeds.rb, lib/templates/erb/scaffold/_form.html.erb, package.json, test/models/offer_test.rb, yarn.lock
code geocoding réaliser, reste à finaliser dans le front
=> réalisation du geocoding

app/assets/stylesheets/components/_test.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_navbar.scss, app/javascript/controllers/index.js, app/javascript/controllers/typed_js_controller.js, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, package.json, yarn.lock
=> hihihiiiiiihahahaaaaaaa

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/pages_controller.rb, app/models/offer.rb, app/models/user.rb, app/views/pages/dashboard.html.erb, db/seeds.rb
les 3 listes fonctionnent presque bien
=> dashboard-amelioration

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/dashboard.html.erb
=> add-card-to-dashboard

app/views/offers/show.html.erb, app/views/pages/profile.html.erb, app/views/shared/_navbar.html.erb
=> sécurisation de la clé API

app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
=> debut-show-booking

app/assets/stylesheets/components/_card.scss, app/views/offers/index.html.erb
réalisation de l'index des offres,
=> réalisation de l'index des offres

app/views/offers/index.html.erb
=> tri-offer-current-id

app/controllers/offers_controller.rb, config/routes.rb
réalisation des: update, new, edit, destroy
plus qu'à passer au front. J'y retourne
=> réalisation des: update, new, edit, destroy

app/controllers/bookings_controller.rb, app/views/bookings/edit.html.erb, config/routes.rb, db/seeds.rb
- mise en place d'une vue qui ressemble à la show `Offer` et qui permet de modifier les dates d'un bookin
=> Update du Booking

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_test.scss, app/assets/stylesheets/components/_text.scss, app/views/pages/dashboard.html.erb
=> color dashboard updated

app/models/booking.rb, app/views/pages/dashboard.html.erb
=> modif-format-date-dashoboard

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_text.scss, app/views/bookings/show.html.erb
=> status-booking

Gemfile, app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/shared/_navbar.html.erb, config/environments/production.rb, config/initializers/devise.rb
j'ai effectué des travaux sur la navbar, sauf que je n'arive pas à la finalisée. De ce fait, je pushhistoire d'être à jour sur ce que j'ai réalisé et je continue les travaux de la navbar. 
Peace ✌🏽
=> réalisation de la navbar

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_map.scss, app/controllers/bookings_controller.rb, app/views/offers/show.html.erb
show offer complétée du booking et du deal
=> show-offers

app/assets/stylesheets/components/_index.scss, app/views/offers/new.html.erb
=> AddImageInNewOffer

app/views/bookings/show.html.erb
rajout des avatars dans le booking
=> rajout des avatars dans le booking

app/assets/stylesheets/components/_avatar.scss, app/views/bookings/show.html.erb
grossisement des avatard du show booking
=> grossisement des avatard du show booking

app/views/bookings/show.html.erb, db/seeds.rb
=> ajout des tel dans la seed

app/assets/stylesheets/components/_showbooking.scss, app/views/bookings/show.html.erb
les fantomes sont de retours sur la show du booking
=> les fantomes sont de retours

app/views/offers/show.html.erb
ajout de l'avatar sur la show de l'offer
=> ajout de l'avatar sur la show de l'offer
